name: Publish on CDN

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      environment_short:
        type: string
        required: true
      
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev
        - uat
        - prod

env:
  STORAGE_ACCOUNT_NAME: "selc${{ inputs.environment_short }}checkoutsa"
  STORAGE_ACCOUNT_RG: "selc-${{ inputs.environment_short }}-checkout-fe-rg"
  CDN_PROFILE_NAME: "selc-${{ inputs.environment_short }}-checkout-cdn-profile"
  CDN_ENDPOINT: "selc-${{ inputs.environment_short }}-checkout-cdn-endpoint"
  CDN_RESOURCE_GROUP: "selc-${{ inputs.environment_short }}-checkout-fe-rg"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:

  publish:
    name: Publish to ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}-cd
    permissions:
      id-token: write
      pull-requests: write

    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Azure Login
        id: az_login
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_CD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to blob storage
        id: storage_upload
        uses: azure/CLI@b0e31ae20280d899279f14c36e877b4c6916e2d3
        with:
          inlineScript: |
            # workaround to escape dollar sign
            container='$web'

            az storage copy \
              --account-name "$STORAGE_ACCOUNT_NAME" \
              --destination-container $container \
              --source './web/resources/logos/*' \
              --destination resources/logos/
              --recursive
     
      - name: Purge CDN endpoint
        uses: azure/CLI@b0e31ae20280d899279f14c36e877b4c6916e2d3
        with:
          inlineScript: |
            az cdn endpoint purge \
              --content-paths '/*' \
              --profile-name "$CDN_PROFILE_NAME" \
              --name "$CDN_ENDPOINT" \
              --content-paths "/resources/logos/*" \
              --resource-group "$CDN_RESOURCE_GROUP"

      - name: Azure Logout
        id: az_logout
        if: always()
        run: |
          az logout