name: Publish on CDN

on:
  push:
    branches:
      - main
    paths:
      - "web/resources/**"

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        default: 'prod'
        options: 
        - dev
        - uat
        - prod
        
jobs:
  release_dev:
    uses: ./.github/workflows/call_publish_cdn.yml
    name: '[DEV] Onboarding-cdc ms Release'
    if: ${{ inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev
      environment_short: d

  release_uat:
    uses: ./.github/workflows/call_publish_cdn.yml
    name: '[UAT] Onboarding-cdc ms Release'
    if: ${{ inputs.env == 'uat' }}
    secrets: inherit
    with:
      environment: uat
      environment_short: u

  release_prod:
    uses: ./.github/workflows/call_publish_cdn.yml
    name: '[PROD] Onboarding-cdc ms Release'
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      environment: prod
      environment_short: p
